# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\"7\n\rClientMessage\x12\x12\n\naws_script\x18\x01 \x01(\t\x12\x12\n\ngcp_script\x18\x02 \x01(\t\"9\n\rServerMessage\x12\x13\n\x0b\x63pu_results\x18\x01 \x01(\t\x12\x13\n\x0bgpu_results\x18\x02 \x01(\t2:\n\x0bTaskService\x12+\n\x07RunTask\x12\x0e.ClientMessage\x1a\x0e.ServerMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTMESSAGE._serialized_start=15
  _CLIENTMESSAGE._serialized_end=70
  _SERVERMESSAGE._serialized_start=72
  _SERVERMESSAGE._serialized_end=129
  _TASKSERVICE._serialized_start=131
  _TASKSERVICE._serialized_end=189
# @@protoc_insertion_point(module_scope)
